sudo: required
language: python

services:
  - docker
  
install:
  - docker build -t davvdg/micmac-docker .
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  
script:
  - docker run -ti davvdg/micmac-docker mm3d CheckDependencies
